### ISSUE TITLE
broken gulpfile

### ISSUE THREAD

**Issue by davidmoshal** [cbaatz/courier-architecture-example#1]
interesting package.
one fix:

```
change: 
var package    = require('package.json');
to
var package    = require('./package.json');
```

**Comment by cbaatz** [comment]
Thanks for reporting the issue! Should be fixed now together with a tidy up of the Gulpfile. Glad you found the concept interesting. Let me know if you have any questions.

**Comment by davidmoshal** [comment]
Have you thought about creating a mixin and/or decorator for react classes?

**Comment by cbaatz** [comment]
No I can't say I have. What did you have in mind?

**Comment by davidmoshal** [comment]
decorating the react class so that it binds automatically, like mobservables, baobab, and others do.
Dave

**Comment by cbaatz** [comment]
Ah, I see. Yes, that would be possible and I can see that it would be more convenient. My personal preference however is that the binding method is explicit in the main file so that the "main loop" so to speak is clear by inspection of the main file.
